services:
  - type: web
    name: web2pdf
    env: python
    buildCommand: |
      apt-get update && apt-get install -y wget ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libcups2 libdbus-1-3 libdrm2 libgbm1 libnspr4 libnss3 libxcomposite1 libxdamage1 libxrandr2 xdg-utils
      pip install -r requirements.txt
      playwright install --with-deps
    startCommand: gunicorn app:app