services:
  - type: web
    name: web2pdf
    env: python
    buildCommand: |
      chmod +x render-build.sh
      ./render-build.sh
      pip install -r requirements.txt
    startCommand: |
      playwright install chromium && gunicorn run:app
